arb-dir: lib/localization
output-dir: lib/localization/generated
template-arb-file: app_en.arb
output-localization-file: localizations.dart
output-class: L10n
nullable-getter: false
synthetic-package: false
untranslated-message-file: lib/localization/generated/untranslated_string.txt
header: '// ignore_for_file: always use package imports'
preferred-supported-locales:
  - en
  - uz