name: talky
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  another_flutter_splash_screen: ^1.2.1
  cached_network_image: ^3.4.1
  cloud_firestore: ^4.17.5
  email_otp: ^3.0.2
  file_picker: ^8.1.3
  firebase_app_check: ^0.2.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.5
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0
  otp_pin_field: ^1.2.9+1
  photo_view: ^0.15.0
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  lines_longer_than: ^1.0.3
  dart_code_metrics: 5.7.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
