// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyUg5pt6pJpYwOsffU4zQRVYQEyTPVYhk',
    appId: '1:374353091800:android:6ebb1fcbfbbf4e5d458bad',
    messagingSenderId: '374353091800',
    projectId: 'talky-test-signin',
    storageBucket: 'talky-test-signin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAlAcH5EO0dlvOstfb4H5UuyMBq5EpG1c',
    appId: '1:374353091800:ios:ac65ceaa69c4e010458bad',
    messagingSenderId: '374353091800',
    projectId: 'talky-test-signin',
    storageBucket: 'talky-test-signin.appspot.com',
    androidClientId: '374353091800-kkuirgk2g1p9mitj2tgguva5ha4bmnmf.apps.googleusercontent.com',
    iosClientId: '374353091800-6rle6oedqs0guro2a5p58pcg6s0mlkoc.apps.googleusercontent.com',
    iosBundleId: 'com',
  );

}